const Ingredient = require('../models/Ingredient');

const ingredientData = [ 
    { name: "Flour" },
    { name: "Sugar" },
    { name: "Salt" },
    { name: "Butter" },
    { name: "Eggs" },
    { name: "Milk" },
    { name: "Cream" },
    { name: "Yogurt" },
    { name: "Cheese" },
    { name: "Bread" },
    { name: "Rice" },
    { name: "Pasta" },
    { name: "Tomatoes" },
    { name: "Onions" },
    { name: "Garlic" },
    { name: "Peppers" },
    { name: "Carrots" },
    { name: "Celery" },
    { name: "Potatoes" },
    { name: "Sweet Potatoes" },
    { name: "Pumpkin" },
    { name: "Broccoli" },
    { name: "Cauliflower" },
    { name: "Spinach" },
    { name: "Lettuce" },
    { name: "Cabbage" },
    { name: "Cucumbers" },
    { name: "Zucchini" },
    { name: "Squash" },
    { name: "Beans" },
    { name: "Peas" },
    { name: "Lentils" },
    { name: "Chickpeas" },
    { name: "Tofu" },
    { name: "Chicken" },
    { name: "Beef" },
    { name: "Pork" },
    { name: "Fish" },
    { name: "Shrimp" },
    { name: "Crab" },
    { name: "Lobster" },
    { name: "Scallops" },
    { name: "Soy Sauce" },
    { name: "Vinegar" },
    { name: "Oil" },
    { name: "Honey" },
    { name: "Mustard" },
    { name: "Mayonnaise" },
    { name: "Ketchup" },
    { name: "Hot Sauce" },
];

const seedIngredients = () => Ingredient.bulkCreate(ingredientData);
module.exports = seedIngredients;
